# Generated by Django 5.2.7 on 2025-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_bill_updated_at_patient_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
