# Generated by Django 5.2.7 on 2025-10-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_bill_due_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='patients.bill')),
            ],
        ),
    ]
